### ISSUE TITLE
compute CC of BinaryHeapArray::heapDown() and document the purpose of each branch (in comments)

### ISSUE THREAD

**Issue by OLGKAD** [OLGKAD/sef18group15-coverage#1]

**Comment by OLGKAD** [comment]
The answer I get is different from Clover's. Can someone manually recalculate the CC of heapDown() to compare the results?

**Comment by pwnttm** [comment]
Computed it manually, got a result differing abit from my output from lizard what did clover show?

**Comment by OLGKAD** [comment]
@pwnttm, Clover returned 41, while I got 38.
